### PR TITLE
Remove everything to do with views

### LINKED ISSUE #2: Remove everything to do with views
This app will be an API serving JSON, so no views needed.

### PR DESCRIPTION
**Pull request by mboneil10**
Closes #2

### CODE REVIEW

**Comment by dfaulken** [comment]
This app isn't deployed yet - feel free to just push to master for now.

**Comment by mboneil10** [comment]
Oh okay, I didn't understand what you meant. I'll do that from now on.

**Comment by ennukee** [comment]
I dunno, I think using PRs is a good idea regardless of whether or not the app is deployed. It serves well as a documentation of past changes so we can see the past of the app as it is created.

**Comment by tomecho** [comment]
image

**Comment by dfaulken** [comment]
@enragednuke I agree, and I was planning on revisiting it once it came time to write actual code.

We're just doing app setup for now, no logic yet.

**Comment by ennukee** [comment]
Okiedokie.

image

**Pull request merged**
